In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("quikr_car.csv")
df.head(3)
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [2]:
df.isnull().sum()
df.duplicated().sum()
df["year"].unique()
# df["kms_driven"].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

# Cleaning Data

In [3]:
df = df[df["year"].str.isnumeric()]

In [4]:
df["year"] = df["year"].astype(int)

In [5]:
df = df[df["Price"] != "Ask For Price"]

In [6]:
df["Price"] = df["Price"].str.replace(",","").astype(int)

In [7]:
df["kms_driven"] = df["kms_driven"].str.split(" ").str.get(0)
df["kms_driven"] = df["kms_driven"].str.replace(",","")
df = df[df["kms_driven"].str.isnumeric()]

In [8]:
df["kms_driven"] = df["kms_driven"].astype(int)

In [9]:
df["fuel_type"] = df["fuel_type"].dropna()

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.7+ KB

In [11]:
df["name"] = df["name"].str.split(" ").str.slice(0,3).str.join(" ")

In [12]:
df = df.reset_index(drop=True)

In [13]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
812      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
813          Tata Indica V2      Tata  2009  110000       30000    Diesel
814    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
815            Tata Zest XM      Tata  2018  260000       27000    Diesel
816      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[817 rows x 6 columns]

In [14]:
df.describe()

              year         Price     kms_driven
count   817.000000  8.170000e+02     817.000000
mean   2012.440636  4.115503e+05   46250.714810
std       4.002354  4.749173e+05   34283.745254
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.900000e+05   56758.000000
max    2019.000000  8.500003e+06  400000.000000

In [15]:
df = df[df["Price"] <= 6000000].reset_index(drop=True)

In [16]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [ ]:
df.to_csv("clean_data.csv")